


set_property PACKAGE_PIN R2 [get_ports {A[3]}]
set_property PACKAGE_PIN T1 [get_ports {A[2]}]
set_property PACKAGE_PIN U1 [get_ports {A[1]}]
set_property PACKAGE_PIN W2 [get_ports {A[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[0]}]
set_property PACKAGE_PIN R3 [get_ports {B[3]}]
set_property PACKAGE_PIN T2 [get_ports {B[2]}]
set_property PACKAGE_PIN T3 [get_ports {B[1]}]
set_property PACKAGE_PIN V2 [get_ports {B[0]}]
set_property PACKAGE_PIN U15 [get_ports {Result[5]}]
set_property PACKAGE_PIN W18 [get_ports {Result[4]}]
set_property PACKAGE_PIN V19 [get_ports {Result[3]}]
set_property PACKAGE_PIN U19 [get_ports {Result[2]}]
set_property PACKAGE_PIN E19 [get_ports {Result[1]}]
set_property PACKAGE_PIN U16 [get_ports {Result[0]}]
set_property PACKAGE_PIN W16 [get_ports Reset]
set_property IOSTANDARD LVCMOS33 [get_ports Reset]
set_property IOSTANDARD LVCMOS33 [get_ports {Result[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Result[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Result[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Result[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Result[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Result[0]}]


set_property PACKAGE_PIN V16 [get_ports s0]
set_property PACKAGE_PIN V17 [get_ports s1]
set_property IOSTANDARD LVCMOS33 [get_ports s0]
set_property IOSTANDARD LVCMOS33 [get_ports s1]



set_property PACKAGE_PIN R2 [get_ports {Ain[3]}]
set_property PACKAGE_PIN T1 [get_ports {Ain[2]}]
set_property PACKAGE_PIN U1 [get_ports {Ain[1]}]
set_property PACKAGE_PIN W2 [get_ports {Ain[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Ain[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Ain[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Ain[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Ain[0]}]
set_property PACKAGE_PIN V13 [get_ports {ALUout[8]}]
set_property PACKAGE_PIN V14 [get_ports {ALUout[7]}]
set_property PACKAGE_PIN U14 [get_ports {ALUout[6]}]
set_property PACKAGE_PIN U15 [get_ports {ALUout[5]}]
set_property PACKAGE_PIN W18 [get_ports {ALUout[4]}]
set_property PACKAGE_PIN V19 [get_ports {ALUout[3]}]
set_property PACKAGE_PIN U19 [get_ports {ALUout[2]}]
set_property PACKAGE_PIN E19 [get_ports {ALUout[1]}]
set_property PACKAGE_PIN U16 [get_ports {ALUout[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ALUout[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ALUout[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ALUout[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ALUout[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ALUout[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ALUout[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ALUout[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ALUout[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ALUout[0]}]
set_property PACKAGE_PIN W15 [get_ports {sel[1]}]
set_property PACKAGE_PIN W17 [get_ports {sel[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[0]}]
set_property PACKAGE_PIN R3 [get_ports {Bin[3]}]
set_property PACKAGE_PIN T2 [get_ports {Bin[2]}]
set_property PACKAGE_PIN T3 [get_ports {Bin[1]}]
set_property PACKAGE_PIN V2 [get_ports {Bin[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Bin[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Bin[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Bin[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Bin[0]}]
